### ISSUE TITLE
Request for Dataset Details - Perceiver-Music-Transformer in Music Cognition Research

### ISSUE THREAD

**Issue by Xiaoxuan-Wang** [asigalov61/Perceiver-Music-Transformer#5]
Dear Alex,

My name is Xiaoxuan, and I am a graduate student at the University of Cambridge, Centre for Music and Science. I am currently working on a research project under the supervision of Dr. Peter MC Harrison. Our focus is on employing deep learning to model music cognition, specifically by adapting autoregressive music generation models into perception models. These perception models will report the surprise (based on probability) at each note in a given musical sequence, similar to a human participant. Your implementation of the Perceiver AR model (Perceiver-Music-Transformer) appears to be a perfect fit for our research.

However, as the model learns musical structures in a self-supervised manner, it is vital to examine these "black boxes" through a cognitive science lens. We are developing psychological paradigms to test the musical structures learned by the models and their learning process. In these tests, it is crucial to know the models' exposure, as unbiased stimuli design depends on it. If the stimuli contain exact phrases that the model has already been trained with, we would only be testing the model's memory instead of its general understanding of musical structures.

Therefore, I am writing to request more detailed information about the dataset (GIGA-Piano & Euterpe Training Data) you used to train the solo-piano and multi-instrumental models.

If you are interested, we can arrange a Zoom meeting for a more in-depth discussion of our research project. My email address is xw407@cam.ac.uk

Best,
Xiaoxuan

**Comment by asigalov61** [comment]
@Xiaoxuan-Wang Thank you for writing. I will contact you soon with the requested info. I was sorta on vacation and busy with other projects so please give me some time :)

Otherwise, I would love to chat and share my knowledge/experience :)

**Comment by Xiaoxuan-Wang** [comment]
Thank you for taking the time to respond to my message! Looking forward to chatting and learning from your experience when you're ready.

Enjoy your vacation and your current projects :)

**Comment by asigalov61** [comment]
@Xiaoxuan-Wang Hey Xiaoxuan. I responded in the Discussions section. I hope it's ok. Let me know and I am looking forward to talking with you :)
