### ISSUE TITLE
Training for a set amount of hours

### ISSUE THREAD

**Issue by RazvanBudacaTechquarter** [asigalov61/Perceiver-Music-Transformer#6]
Hi! 
I'm a 3rd year student from Romania and for my bachelor's project I'm using your implementation and another model to generate single-instrument traditional Romanian music from scratch. I basically want to compare 2 different models and see which one performs better on this task.

To compare fairly, I was thinking to let each model train for about 12 hours on a dataset of ~62h of content (basically all I could find on the internet).
Is there a way to set a timer on this model, or let it continuously train until I stop it?

**Comment by asigalov61** [comment]
Hey @BudiGabe 

Perceiver is very tricky and difficult to work with when it comes to data feeding....so if you have a relatively small dataset, I do not know if continuous training will work at all...

But if you want to try it, you will need to adjust the dataloader code in the training code...

For example, you can change this:

```
class MusicDataset(Dataset):
    def __init__(self, data, seq_len):
        super().__init__()
        self.data = data
        self.seq_len = seq_len

    def __getitem__(self, index):
        
        # consequtive sampling
        idx = index * self.seq_len
   
        full_seq = self.data[idx: idx + self.seq_len + 1].long()
        
        return full_seq.cuda()

    def __len__(self):
        return (self.data.size(0) // self.seq_len // BATCH_SIZE) * BATCH_SIZE
```

To this:

```
class MusicDataset(Dataset):
    def __init__(self, data, seq_len):
        super().__init__()
        self.data = data
        self.seq_len = seq_len

    def __getitem__(self, index):
        
        # random sampling
        
        idx = secrets.randbelow(self.data.size(0) - self.seq_len - 1)
        full_seq = self.data[idx: idx + self.seq_len + 1].long()
        
        return full_seq.cuda()

    def __len__(self):
        return self.data.size(0)
```

Then, set NUM_BATCHES variable to some arbitrary value you want (i.e 100000)

However, please note that Perceiver can't handle random sampling very well, so you will need to figure out a way to avoid it and you will need to adjust your code accordingly.

Hope this helps.

Alex.

**Comment by RazvanBudacaTechquarter** [comment]
Thanks a lot for the quick answer!
The dataset is indeed small, but it's as long as POP909 and I see in the discussions tab that you already tried it and got some decent results. Hopefully the same will go for me!

**Comment by asigalov61** [comment]
@BudiGabe Np. Have fun! :) And if you need more help, feel free to write :)
